import "./globals.css";
import "./styles.css";
import "locomotive-scroll/locomotive-scroll.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Navbar from "./Components/UI/Navbar/Navbar";
import SmoothScroll from "./Components/UI/SmoothScroll/SmoothScroll";
import TransitionProviders from "./Components/Providers/TransitionProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        <Navbar />
        <TransitionProviders>
          {children}
        </TransitionProviders>
        <SpeedInsights />
      </body>
    </html>
  );
}
